version: '3'
services:
  php:
   build:
    ./php
   ports:
    - 80:80
   volumes: 
    - ./www/:/var/www/html
    - ./php/php.ini:/usr/local/etc/php/php.ini
   depends_on:
    - mariadb


    
  mariadb:
   image: mariadb:10.5.1
   volumes:
    - ./mariadb:/var/lib/mysql
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
   ports:
    - "3306:3306"



  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   links: 
    - mariadb:db
   ports:
    - 8080:80
   environment:
    MYSQL_ROOT_PASSWORD: root
   depends_on:
    - mariadb
